update stderrPipe*

diff --git a/unity3d-installer b/unity3d-installer
--- a/unity3d-installer
+++ b/unity3d-installer
@@ -1,22 +1,27 @@
 #!/usr/bin/env bash
 set -eE -o pipefail
 
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeDebug=' exec awk "{print \"\\033[00m$(date +%Y-%m-%dT%H:%M:%S%z) [  debug] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeDebug
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeNotice='exec awk "{print \"\\033[01m$(date +%Y-%m-%dT%H:%M:%S%z) [ notice] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeNotice
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeError=' exec awk "{print \"\\033[31m$(date +%Y-%m-%dT%H:%M:%S%z) [  error] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeError
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeOK='    exec awk "{print \"\\033[32m$(date +%Y-%m-%dT%H:%M:%S%z) [     ok] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeOK
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeWarn='  exec awk "{print \"\\033[33m$(date +%Y-%m-%dT%H:%M:%S%z) [warning] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeWarn
+# shellcheck disable=SC2016,SC2089,SC2090
+stderrPipeInfo='  exec awk "{print \"\\033[34m$(date +%Y-%m-%dT%H:%M:%S%z) [   info] \"\$0\"\\033[0m\"}" /dev/stdin 1>&2' && export stderrPipeInfo
+
 # const
 declare -r PROG_NAME=unity3d-installer                                               && export PROG_NAME
 declare -r UNITY_DOWNLOAD_ARCHIVE_URL=https://unity3d.com/get-unity/download/archive && export UNITY_DOWNLOAD_ARCHIVE_URL
 declare -r SEPARATOR='\t'                                                            && export SEPARATOR
 
-# function stderr
-stderrPipeDebug ()  { awk '{print "\033[00m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [  debug] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeDebug
-stderrPipeNotice () { awk '{print "\033[01m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [ notice] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeNotice
-stderrPipeError ()  { awk '{print "\033[31m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [  error] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeError
-stderrPipeOK ()     { awk '{print "\033[32m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [     ok] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeOK
-stderrPipeWarn ()   { awk '{print "\033[33m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [warning] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeWarn
-stderrPipeInfo ()   { awk '{print "\033[34m'"$(date +%Y-%m-%dT%H:%M:%S%z)"' [   info] "$0"\033[0m"}' /dev/stdin 1>&2; } && export -f stderrPipeInfo
-
 # function 1
 selectWritableDir () { for path in "$@"; do [ ! -w "${path}" ] || { echo -n "${path}"; return 0; }; done }
-checkSupportOS () { if ! uname -s | grep -q Linux; then echo "OS not supported." | stderrPipeError; exit 1; fi; }
+checkSupportOS () { if ! uname -s | grep -q Linux; then echo "OS not supported." | sh -c "${stderrPipeError:?}"; exit 1; fi; }
 
 # var
 # shellcheck disable=SC2155
@@ -29,7 +34,7 @@ declare -r UnitySetupURLCSVFile="${StoredDir:?}/.${PROG_NAME:?}.csv"      && exp
 
 function CreateOrUpdateUnitySetupURLCSVFile () { (
   if [[ $* =~ .*-f.*|.*--fource.* ]] ||  [[ ! -r ${UnitySetupURLCSVFile:?} ]] || [[ ! -s ${UnitySetupURLCSVFile:?} ]]; then
-    echo "Generating a UnitySetup URL csv file as ${UnitySetupURLCSVFile:?} ..." | stderrPipeInfo
+    echo "Generating a UnitySetup URL csv file as ${UnitySetupURLCSVFile:?} ..." | sh -c "${stderrPipeInfo:?}"
     csvData=$(
       # CSV header
       printf "%s${SEPARATOR:?}%s${SEPARATOR:?}%s\n" "version" "status" "url"
@@ -44,32 +49,32 @@ function CreateOrUpdateUnitySetupURLCSVFile () { (
     )
     echo "${csvData:?}" >"${UnitySetupURLCSVFile:?}"
   fi
-  echo "UnitySetup URL csv file was saved as ${UnitySetupURLCSVFile:?}" | stderrPipeInfo
+  echo "UnitySetup URL csv file was saved as ${UnitySetupURLCSVFile:?}" | sh -c "${stderrPipeInfo:?}"
 )}
 
 
 
 function InstallUnity () { (
   if [[ ! $* =~ install.*[[:blank:]]*[[:blank:]]+[^\.]+\.[^\.]+\.[^\.]+ ]]; then
-    echo "Specify Unity version." | stderrPipeError
+    echo "Specify Unity version." | sh -c "${stderrPipeError:?}"
     exit 1
   fi
   # shellcheck disable=SC2001
   specified_version=$(echo "$*" | sed "s@install.*[[:blank:]]*[[:blank:]][[:blank:]]*\([^\.][^\.]*\.[^\.][^\.]*\.[^\.][^\.]*\).*@\1@")
   specified_version_escaped_regex=${specified_version//\./\\.}
   if ! grep -q "^${specified_version_escaped_regex}" "${UnitySetupURLCSVFile:?}"; then
-    echo "Specify the version of Unity that can be installed." | stderrPipeError
+    echo "Specify the version of Unity that can be installed." | sh -c "${stderrPipeError:?}"
     exit 1
   fi
   url=$(grep "^${specified_version_escaped_regex}" "${UnitySetupURLCSVFile:?}" | awk -F"${SEPARATOR:?}" "\$0=\$3")
-  echo "Download ${url:?} as AAAA" | stderrPipeInfo
+  echo "Download ${url:?} as AAAA" | sh -c "${stderrPipeInfo:?}"
 )}
 
 
 
 function ListInstallableVersions () { (
   if [[ ! -r ${UnitySetupURLCSVFile:?} ]] || [[ ! -s ${UnitySetupURLCSVFile:?} ]]; then
-    echo "UnitySetup URL csv file not found." | stderrPipeWarn
+    echo "UnitySetup URL csv file not found." | sh -c "${stderrPipeWarn:?}"
   fi
   versions=$(
     grep -E "[^${SEPARATOR:?}]+${SEPARATOR:?}200${SEPARATOR:?}[^${SEPARATOR:?}]+" "${UnitySetupURLCSVFile:?}" \
